// Package auth holds the one secret k8n has: the token that pairs a browser
// with this process.
//
// Every route here can read and change a Kubernetes cluster, and until now the
// only thing standing in front of them was the loopback bind — which stops
// another machine, but not another program on this one, and not a web page you
// happen to have open. A page on the internet cannot read this token (it is in
// another origin's storage), so requiring it closes the browser-driven attacks
// that CORS alone does not: a cross-site POST, and a DNS rebind that makes the
// attacker's page look same-origin.
//
// It is a pairing secret, not an authentication system. It says "this browser
// is the one the user pasted the token into". It does not identify a user, and
// it is not enough on its own to put k8n on a public address.
package auth

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Header is the preferred way to present the token. The query parameter exists
// because EventSource cannot set headers, and the cluster watch is an
// EventSource.
const (
	Header      = "X-K8n-Token"
	QueryParam  = "t"
	altQueryKey = "token"
)

// Disabled reports whether the operator has turned pairing off. For a trusted
// network behind something that already authenticates — never for a laptop.
func Disabled() bool {
	return strings.EqualFold(os.Getenv("K8N_NO_AUTH"), "true")
}

// Load returns the token for this instance: K8N_TOKEN if set, otherwise the one
// saved in ~/.k8n/token, otherwise a fresh one which is then saved. Keeping it
// on disk means restarting k8n does not invalidate the tab you have open.
func Load() (string, error) {
	if fromEnv := strings.TrimSpace(os.Getenv("K8N_TOKEN")); fromEnv != "" {
		return fromEnv, nil
	}

	path, err := tokenPath()
	if err != nil {
		return "", err
	}

	if saved, err := os.ReadFile(path); err == nil {
		if token := strings.TrimSpace(string(saved)); token != "" {
			return token, nil
		}
	}

	token, err := generate()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return "", fmt.Errorf("could not create %s: %w", filepath.Dir(path), err)
	}
	// 0600: readable by this user only. Windows ignores the mode, which is why
	// the token is short-lived in the sense that it can be regenerated by
	// deleting this file — not in the sense that it expires.
	if err := os.WriteFile(path, []byte(token), 0o600); err != nil {
		return "", fmt.Errorf("could not write %s: %w", path, err)
	}
	return token, nil
}

func tokenPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("could not find your home directory: %w", err)
	}
	return filepath.Join(home, ".k8n", "token"), nil
}

func generate() (string, error) {
	raw := make([]byte, 32)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("could not generate a token: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(raw), nil
}

// Presented pulls the token out of a request, in the order a caller would most
// likely send it.
func Presented(header func(string) string, query func(string) string) string {
	if v := strings.TrimSpace(header(Header)); v != "" {
		return v
	}
	if v := strings.TrimSpace(header("Authorization")); strings.HasPrefix(v, "Bearer ") {
		return strings.TrimSpace(strings.TrimPrefix(v, "Bearer "))
	}
	if v := strings.TrimSpace(query(QueryParam)); v != "" {
		return v
	}
	return strings.TrimSpace(query(altQueryKey))
}

// Matches compares in constant time, so a wrong token tells an attacker nothing
// about how much of it was right.
func Matches(want, got string) bool {
	return len(got) > 0 && subtle.ConstantTimeCompare([]byte(want), []byte(got)) == 1
}

// Redact hides the token in anything about to be printed — the request log
// includes the query string, and the whole point is that it does not leak.
func Redact(path string) string {
	cut := strings.IndexByte(path, '?')
	if cut < 0 {
		return path
	}

	params := strings.Split(path[cut+1:], "&")
	for i, param := range params {
		for _, key := range []string{QueryParam, altQueryKey} {
			if strings.HasPrefix(param, key+"=") {
				params[i] = key + "=REDACTED"
			}
		}
	}
	return path[:cut+1] + strings.Join(params, "&")
}
